<a href="https://colab.research.google.com/github/pleabargain/ipynb_notebooks/blob/master/climate_measurement_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install --upgrade 'notebook>=5.7.6'
!pip install --upgrade 'numpy'

    100% |████████████████████████████████| 9.0MB 897kB/s 
google-colab 1.0.0 has requirement notebook~=5.2.0, but you'll have notebook 5.7.6 which is incompatible.
  Found existing installation: notebook 5.2.2
    Uninstalling notebook-5.2.2:
      Successfully uninstalled notebook-5.2.2
    100% |████████████████████████████████| 17.3MB 2.1MB/s 
featuretools 0.4.1 has requirement pandas>=0.23.0, but you'll have pandas 0.22.0 which is incompatible.
datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.8 which is incompatible.
  Found existing installation: numpy 1.14.6
    Uninstalling numpy-1.14.6:
      Successfully uninstalled numpy-1.14.6


In [1]:
import numpy
numpy.version.version

'1.16.2'

In [0]:
import numpy as np

#temperatures = csv_array = np.genfromtxt('temperature_data.csv', delimiter=',')

In [9]:
#don't forget the parens!
arr_temp =np.array([[ 43.6,  45.1,  58.8 , 53. ],
 [ 47, 44.5,  58.3,  52.6],
 [ 46.7 , 44.2 , 57.9 , 52.2],
 [ 46.5  ,44.1 , 57.6,  51.9],
 [ 46.2 , 43.9,  57.2 , 51.5]])
arr_temp



array([[43.6, 45.1, 58.8, 53. ],
       [47. , 44.5, 58.3, 52.6],
       [46.7, 44.2, 57.9, 52.2],
       [46.5, 44.1, 57.6, 51.9],
       [46.2, 43.9, 57.2, 51.5]])

In [10]:
import numpy as np

#temperatures = np.genfromtxt('temperature_data.csv', delimiter=',')

print(arr_temp)

temperatures_fixed = arr_temp + 3

print(temperatures_fixed)

monday_temperatures = temperatures_fixed[0,:]
#at 0600
thursday_friday_morning = temperatures_fixed[3:5,1]
print(thursday_friday_morning)


temperature_extremes = temperatures_fixed[(temperatures_fixed < 50) | (temperatures_fixed > 60)]

[[43.6 45.1 58.8 53. ]
 [47.  44.5 58.3 52.6]
 [46.7 44.2 57.9 52.2]
 [46.5 44.1 57.6 51.9]
 [46.2 43.9 57.2 51.5]]
[[46.6 48.1 61.8 56. ]
 [50.  47.5 61.3 55.6]
 [49.7 47.2 60.9 55.2]
 [49.5 47.1 60.6 54.9]
 [49.2 46.9 60.2 54.5]]
[47.1 46.9]
